# Generated by Django 5.2.6 on 2025-09-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        # SQL --> if ORM can not fulfil.
        migrations.RunSQL(
# Upgrading
"""
INSERT INTO store_collection (title)
VALUES ('collection_one')
"""
,
# Downgrading
"""
DELETE FROM store_collection
WHERE title = 'collection_one'
"""
        )
    ]
